#!/usr/bin/bash

# Variables
config=$HOME/.config/hypr
scripts=$config/scripts

# Notification Daemon
dunst &

# Eye Protection
# wlsunset -l 90.0:0.0 -t 4000 &
wlsunset -l 0.0:90.0 -t 4000 &

# Record Screen
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &

# Status Bar
waybar &
# exec-once = eww -c $HOME/.config/eww/bar/ open bar

# Input Method
fcitx5 -dr &

# Wallpaper
# swww init
# swww img ~/wall/pics/top/30.jpg &
mpvpaper -o "no-audio loop" eDP-1 ~/Wallpaper/video/dongman/deepsea.mp4 &
mpvpaper -o "no-audio loop" HDMI-A-1 ~/Wallpaper/video/dongman/platfrom.mp4 &

# Other
$scripts/battery_notification &
# $scripts/idle_handler &
# qqmusic &

# Proxy
cfw &
