theme = "mytheme"

[editor]
line-number = "relative"
mouse = true
auto-completion = true
completion-trigger-len = 4
auto-info = true


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

#[editor.whitespace]
#render = "all"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "·"
newline = "⏎"
